feat: parse and clean archive badges and markdown links to URL
pyOpenSci/pyosMeta pull request #243
Opened 2024-12-15 06:02 UTC by banesullivan

This will parse markdown links/badges to consistently capture a URLs from the archive and JOSS DOI fields.

Note that this adds https://github.com/papis/python-doi as a dependency

2024-12-19 19:12 UTC, lwasser commented
hey @banesullivan i'll leave some more specific feedback here but it looks like 

1. this is erroring on a review (bibat) which means there is an outlier format in archive that isn't being handled as we would like it to be handled. 

```
update-reviews
/Users/leahawasser/Documents/GitHub/pyos/pyosMeta/src/pyosmeta/parse_issues.py:489: UserWarning: ## Community Partnerships not found in the list
  warnings.warn(f"{section_str} not found in the list")
Error in review at url: https://api.github.com/repos/pyOpenSci/software-submission/issues/83
Traceback (most recent call last):

  File "/Users/leahawasser/Documents/GitHub/pyos/pyosMeta/src/pyosmeta/parse_issues.py", line 310, in parse_issues
    review = self.parse_issue(issue)

  File "/Users/leahawasser/Documents/GitHub/pyos/pyosMeta/src/pyosmeta/parse_issues.py", line 284, in parse_issue
    return ReviewModel(**model)

  File "/Users/leahawasser/mambaforge/envs/pyosmeta/lib/python3.10/site-packages/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)

pydantic_core._pydantic_core.ValidationError: 1 validation error for ReviewModel
joss
  Value error, Invalid archive URL:  [type=value_error, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/value_error

--------------------
http://www.sunpy.org 'http://' replacing w 'https://'
http://sourmash.readthedocs.io/en/latest/ 'http://' replacing w 'https://'
http://movingpandas.org 'http://' replacing w 'https://'
```

2. When running it locally is that it hangs. I suspect it's slower because adding python-doi means we are parsing and checking urls / DOIs for each package. For now, we might consider adding more output so a user knows it's doing something. Maybe the package name it's processing in the terminal would be good to print out? I almost thought it was broken, and then I saw it was just processing but slower than it was previously.

2025-01-07 21:10 UTC, lwasser requested changes
oops. it looks like i left blocks of feedbak but not the line by line comments. i'm just making sure those are visible now.

2025-01-07 21:13 UTC, lwasser commented
hey @banesullivan i'm checking in on this pr. we are running into the issue that every pr on the website fails CI because of the dois! i think we have two options.

1. we can merge this almost as is and push a new release if it fixes things, then the website will atleast be green.
2. you can work on the tests and other smaller items in a separate pr. 

The above approach is great if you are busy during this first full week back!! 
Alternatively, we can leave this open for a bit longer and fix things here. 

Please let me know what you prefer!

2025-01-13 06:06 UTC, banesullivan commented
> this is erroring on a review (bibat) which means there is an outlier format in archive that isn't being handled as we would like it to be handled.

Whoops! Not sure how I missed this on the first go around. I track this down and it was because the JOSS DOI field was left blank. I have updated the parser/validator to handle missing data like this in b6b9f27

> When running it locally is that it hangs. I suspect it's slower because adding python-doi means we are parsing and checking urls / DOIs for each package. For now, we might consider adding more output so a user knows it's doing something. Maybe the package name it's processing in the terminal would be good to print out? I almost thought it was broken, and then I saw it was just processing but slower than it was previously.

Ooof, I didn't realize how much slower it was until now. Indeed it is the DOI validation step that is causing this slowdown. I can add a print statement, perhaps in [this for-loop](https://github.com/pyOpenSci/pyosMeta/blob/612c046b5241b0f81796f77d98e793c41db1211d/src/pyosmeta/parse_issues.py#L305) to indicate each package it is currently processing. 

With this dramatic of a slow down, I'm considering not doing the full validation of the DOI URLs to ensure they resolve correctly. Perhaps these could be gathered and at the end of critical build steps like for the documentation we check these DOI URLs to validate that the resolve. For now, I'm adding a simple `print` statement in b25ebbc to indicate progress, but I think we should come back to this later.

2025-01-13 06:08 UTC, banesullivan commented on src/pyosmeta/utils_clean.py
> +import doi
Further clarified this in e1246e0

2025-01-13 06:09 UTC, banesullivan commented on src/pyosmeta/utils_clean.py
> +    * Markdown links in the format `[label](URL)`, e.g., `[my archive](https://doi.org/10.1234/zenodo.12345678)`
All good, it was the JOSS DOI field causing the failure as it was left black for https://github.com/pyOpenSci/software-submission/issues/83. The zenodo badge in this example is handle and a recurring pattern on a lot of reviews

2025-01-13 06:23 UTC, banesullivan commented on src/pyosmeta/utils_clean.py
> +            raise ValueError(f"Invalid archive URL: {archive}")
Added more validation testing in a4e9477

2025-01-13 06:37 UTC, banesullivan commented
> I'm also noticing some inconsistency in JOSS ... Both will work! My question is, should we be consistent in how we save the doi and always link to the doi rather than the paper in terms of the data we store in our "database," aka YML file?

I'm not sure! This feels weird to me as the DOIs themselves resoilve to the paper and if I use the `python-doi` package to validate a DOI like `10.21105/joss.05221` i get a link to the paper:

```py
>>> import doi
>>> doi.validate_doi('10.21105/joss.05221')
'https://joss.theoj.org/papers/10.21105/joss.05221'
```

I'm not sure what's best here. This may be something we engage JOSS directly on and follow up.

2025-01-13 06:40 UTC, banesullivan commented
> we are running into the issue that every pr on the website fails CI because of the dois! i think we have two options.

agh! Let's push to merge as is at this point and document any lingering issues like archive URL format inconsistencies for future work

2025-01-14 18:48 UTC, lwasser commented
thank you @banesullivan this is running much better now and isn't erroring. let's merge. I've opened a few issues #248 #247  that we can work on independently. i'm going to merge this and push out a new patch release to see if we can get ci to be happy on the website side of things !! 🤞🏻

2025-01-14 18:48 UTC, lwasser approved these changes

2025-01-14 18:49 UTC, merged